import { createSvgIcon } from "@mui/material/utils";

const ChainIcon = createSvgIcon(
  <svg
    width="70"
    height="70"
    viewBox="18 27 70 70"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g transform="translate(10, 10) rotate(45, 17, 27)">
      <rect
        x="10"
        y="23"
        width="14"
        height="8"
        rx="4"
        ry="4"
        stroke="#F08080"
        strokeWidth="2"
        fill="none"
      />
      <rect
        x="28"
        y="23"
        width="14"
        height="8"
        rx="4"
        ry="4"
        stroke="#F08080"
        strokeWidth="2"
        fill="none"
      />
      <line
        x1="18"
        y1="27"
        x2="34"
        y2="27"
        stroke="#F08080"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </g>
    <g transform="translate(62, 10) rotate(135, 17, 27)">
      <rect
        x="10"
        y="23"
        width="14"
        height="8"
        rx="4"
        ry="4"
        stroke="#F08080"
        strokeWidth="2"
        fill="none"
      />
      <rect
        x="28"
        y="23"
        width="14"
        height="8"
        rx="4"
        ry="4"
        stroke="#F08080"
        strokeWidth="2"
        fill="none"
      />
      <line
        x1="18"
        y1="27"
        x2="34"
        y2="27"
        stroke="#F08080"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </g>
    <g transform="translate(10, 62) rotate(315, 17, 27)">
      <rect
        x="10"
        y="23"
        width="14"
        height="8"
        rx="4"
        ry="4"
        stroke="#F08080"
        strokeWidth="2"
        fill="none"
      />
      <rect
        x="28"
        y="23"
        width="14"
        height="8"
        rx="4"
        ry="4"
        stroke="#F08080"
        strokeWidth="2"
        fill="none"
      />
      <line
        x1="18"
        y1="27"
        x2="34"
        y2="27"
        stroke="#F08080"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </g>
    <g transform="translate(62, 62) rotate(225, 17, 27)">
      <rect
        x="10"
        y="23"
        width="14"
        height="8"
        rx="4"
        ry="4"
        stroke="#F08080"
        strokeWidth="2"
        fill="none"
      />
      <rect
        x="28"
        y="23"
        width="14"
        height="8"
        rx="4"
        ry="4"
        stroke="#F08080"
        strokeWidth="2"
        fill="none"
      />
      <line
        x1="18"
        y1="27"
        x2="34"
        y2="27"
        stroke="#F08080"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </g>
  </svg>,
  "ChainIcon"
);

export default ChainIcon;
